const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");

const rootDir = __dirname;
const port = Number(process.env.PORT || 4173);

const mimeTypes = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8",
};

const apiData = {
  leagues: [
    { id: "liga-1", name: "Primera División", count: 18, logo: "/demo/assets/logos/liga-primera.svg" },
    { id: "liga-2", name: "Primera B", count: 16, logo: "/demo/assets/logos/liga-primera.svg" },
    { id: "liga-3", name: "Copa Chile", count: 14, logo: "/demo/assets/logos/liga-primera.svg" },
    { id: "liga-4", name: "Premier League", count: 20, logo: "/demo/assets/logos/liga-premier.svg" },
    { id: "liga-5", name: "LaLiga", count: 20, logo: "/demo/assets/logos/liga-laliga.svg" },
    { id: "liga-6", name: "Serie A", count: 20, logo: "/demo/assets/logos/liga-seriea.svg" },
    { id: "liga-7", name: "Bundesliga", count: 18, logo: "/demo/assets/logos/liga-bundes.svg" },
    { id: "liga-8", name: "Champions League", count: 12, logo: "/demo/assets/logos/liga-champions.svg" },
    { id: "liga-9", name: "Ligue 1", count: 18, logo: "/demo/assets/logos/liga-ligue1.svg" },
    { id: "liga-10", name: "MLS", count: 14, logo: "/demo/assets/logos/liga-mls.svg" },
    { id: "liga-11", name: "NBA", count: 9, logo: "/demo/assets/logos/liga-nba.svg" },
    { id: "liga-12", name: "NFL", count: 6, logo: "/demo/assets/logos/liga-nfl.svg" },
    { id: "liga-13", name: "MLB", count: 6, logo: "/demo/assets/logos/liga-mlb.svg" },
    { id: "liga-14", name: "ATP Tour", count: 7, logo: "/demo/assets/logos/liga-atp.svg" },
    { id: "liga-15", name: "WTA", count: 6, logo: "/demo/assets/logos/liga-wta.svg" },
    { id: "liga-16", name: "UFC", count: 4, logo: "/demo/assets/logos/liga-ufc.svg" },
    { id: "liga-17", name: "Copa Libertadores", count: 10, logo: "/demo/assets/logos/liga-libertadores.svg" },
    { id: "liga-18", name: "Copa Sudamericana", count: 8, logo: "/demo/assets/logos/liga-sudamericana.svg" },
    { id: "liga-19", name: "Liga MX", count: 18, logo: "/demo/assets/logos/liga-ligamx.svg" },
    { id: "liga-20", name: "EuroLeague", count: 8, logo: "/demo/assets/logos/liga-euroleague.svg" },
    { id: "liga-21", name: "Formula 1", count: 10, logo: "/demo/assets/logos/liga-f1.svg" },
    { id: "liga-22", name: "LoL", count: 8, logo: "/demo/assets/logos/liga-lol.svg" },
    { id: "liga-23", name: "CS2", count: 8, logo: "/demo/assets/logos/liga-cs2.svg" },
    { id: "liga-24", name: "Six Nations", count: 6, logo: "/demo/assets/logos/liga-sixnations.svg" },
    { id: "liga-25", name: "NHL", count: 8, logo: "/demo/assets/logos/liga-nhl.svg" },
    { id: "liga-26", name: "VNL", count: 6, logo: "/demo/assets/logos/liga-vnl.svg" },
    { id: "liga-27", name: "EHF Champions", count: 6, logo: "/demo/assets/logos/liga-ehf.svg" },
    { id: "liga-28", name: "Boxing", count: 5, logo: "/demo/assets/logos/liga-boxing.svg" },
    { id: "liga-29", name: "PDC Darts", count: 5, logo: "/demo/assets/logos/liga-darts.svg" },
    { id: "liga-30", name: "MotoGP", count: 6, logo: "/demo/assets/logos/liga-motogp.svg" },
    { id: "liga-31", name: "PGA Tour", count: 5, logo: "/demo/assets/logos/liga-pga.svg" },
    { id: "liga-32", name: "IPL", count: 8, logo: "/demo/assets/logos/liga-ipl.svg" },
    { id: "liga-33", name: "UCI World Tour", count: 6, logo: "/demo/assets/logos/liga-uci.svg" },
  ],
  banners: [
    {
      id: "bn-1",
      title: "Bono de bienvenida",
      subtitle: "+20% en apuestas demo",
      cta: "Activar bono",
      icon: "/demo/assets/icons/bolt.svg",
      image: "/demo/assets/banners/bonus.svg",
    },
    {
      id: "bn-2",
      title: "Cashout rápido",
      subtitle: "Retira ganancias antes del cierre",
      cta: "Ver opciones",
      icon: "/demo/assets/icons/coin.svg",
      image: "/demo/assets/banners/cashout.svg",
    },
    {
      id: "bn-3",
      title: "Ligas en vivo",
      subtitle: "Seguimiento en tiempo real",
      cta: "Explorar",
      icon: "/demo/assets/icons/trophy.svg",
      image: "/demo/assets/banners/live.svg",
    },
  ],
  markets: [
    {
      id: "mkt-1",
      category: "Fútbol",
      league: "Primera División",
      title: "Colo-Colo vs Universidad de Chile",
      description: "Resultado final del clásico.",
      source: "ANFP / marcador oficial",
      close_at: "2026-03-20T18:00",
      status: "abierto",
      liquidity: 340000,
      participants: 42,
      confidence: 61,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-colo-colo.svg",
      awayLogo: "/demo/assets/logos/team-la-u.svg",
    },
    {
      id: "mkt-2",
      category: "Fútbol",
      league: "Primera División",
      title: "Universidad Católica vs Palestino",
      description: "Resultado final del partido.",
      source: "ANFP / marcador oficial",
      close_at: "2026-03-21T20:00",
      status: "abierto",
      liquidity: 210000,
      participants: 31,
      confidence: 52,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-uc.svg",
      awayLogo: "/demo/assets/logos/team-palestino.svg",
    },
    {
      id: "mkt-3",
      category: "Fútbol",
      league: "Premier League",
      title: "Arsenal vs Chelsea",
      description: "Resultado final del partido.",
      source: "Premier League / marcador oficial",
      close_at: "2026-03-23T17:00",
      status: "abierto",
      liquidity: 520000,
      participants: 88,
      confidence: 58,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-ars.svg",
      awayLogo: "/demo/assets/logos/team-che.svg",
    },
    {
      id: "mkt-4",
      category: "Fútbol",
      league: "LaLiga",
      title: "Real Madrid vs Barcelona",
      description: "Clásico español.",
      source: "LaLiga / marcador oficial",
      close_at: "2026-03-24T21:00",
      status: "abierto",
      liquidity: 680000,
      participants: 120,
      confidence: 64,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-rma.svg",
      awayLogo: "/demo/assets/logos/team-bar.svg",
    },
    {
      id: "mkt-5",
      category: "Fútbol",
      league: "Serie A",
      title: "Juventus vs Inter",
      description: "Derby de Italia.",
      source: "Serie A / marcador oficial",
      close_at: "2026-03-25T20:45",
      status: "abierto",
      liquidity: 460000,
      participants: 74,
      confidence: 55,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-juv.svg",
      awayLogo: "/demo/assets/logos/team-int.svg",
    },
    {
      id: "mkt-6",
      category: "Basket",
      league: "NBA",
      title: "Lakers vs Heat",
      description: "Resultado final NBA.",
      source: "NBA / marcador oficial",
      close_at: "2026-03-20T22:15",
      status: "abierto",
      liquidity: 300000,
      participants: 50,
      confidence: 59,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-lakers.svg",
      awayLogo: "/demo/assets/logos/team-heat.svg",
    },
    {
      id: "mkt-7",
      category: "Tenis",
      league: "ATP Tour",
      title: "Alcaraz vs Medvedev",
      description: "Resultado final del partido.",
      source: "ATP / marcador oficial",
      close_at: "2026-03-26T15:40",
      status: "abierto",
      liquidity: 180000,
      participants: 24,
      confidence: 57,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-alcaraz.svg",
      awayLogo: "/demo/assets/logos/team-medvedev.svg",
    },
    {
      id: "mkt-8",
      category: "MMA",
      league: "UFC",
      title: "Pereira vs Hill",
      description: "Evento estelar.",
      source: "UFC / comunicado oficial",
      close_at: "2026-03-27T23:00",
      status: "abierto",
      liquidity: 250000,
      participants: 37,
      confidence: 53,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-9",
      category: "Fútbol",
      league: "Primera División",
      title: "Everton vs Unión Española",
      description: "Resultado final del partido.",
      source: "ANFP / marcador oficial",
      close_at: "2026-03-22T18:30",
      status: "abierto",
      liquidity: 190000,
      participants: 29,
      confidence: 50,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-everton.svg",
      awayLogo: "/demo/assets/logos/team-union.svg",
    },
    {
      id: "mkt-10",
      category: "Fútbol",
      league: "Primera B",
      title: "Wanderers vs Temuco",
      description: "Resultado final del partido.",
      source: "ANFP / marcador oficial",
      close_at: "2026-03-23T16:00",
      status: "abierto",
      liquidity: 120000,
      participants: 18,
      confidence: 48,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-wanderers.svg",
      awayLogo: "/demo/assets/logos/team-temuco.svg",
    },
    {
      id: "mkt-11",
      category: "Fútbol",
      league: "Copa Chile",
      title: "Colo-Colo vs Universidad Católica",
      description: "Llave de eliminación directa.",
      source: "ANFP / marcador oficial",
      close_at: "2026-03-24T19:00",
      status: "abierto",
      liquidity: 260000,
      participants: 38,
      confidence: 56,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-colo-colo.svg",
      awayLogo: "/demo/assets/logos/team-uc.svg",
    },
    {
      id: "mkt-12",
      category: "Fútbol",
      league: "Premier League",
      title: "Arsenal vs Chelsea",
      description: "Resultado final del partido.",
      source: "Premier League / marcador oficial",
      close_at: "2026-03-25T16:30",
      status: "abierto",
      liquidity: 620000,
      participants: 98,
      confidence: 60,
      icon: "/demo/assets/icons/ball.svg",
      homeLogo: "/demo/assets/logos/team-ars.svg",
      awayLogo: "/demo/assets/logos/team-che.svg",
    },
    {
      id: "mkt-13",
      category: "Fútbol",
      league: "Copa Libertadores",
      title: "Flamengo vs River Plate",
      description: "Fase de grupos.",
      source: "CONMEBOL / marcador oficial",
      close_at: "2026-03-26T21:30",
      status: "abierto",
      liquidity: 540000,
      participants: 84,
      confidence: 57,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-14",
      category: "Fútbol",
      league: "Copa Sudamericana",
      title: "São Paulo vs LDU Quito",
      description: "Fase de grupos.",
      source: "CONMEBOL / marcador oficial",
      close_at: "2026-03-27T21:30",
      status: "abierto",
      liquidity: 280000,
      participants: 41,
      confidence: 54,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-15",
      category: "Fútbol",
      league: "Liga MX",
      title: "Club América vs Tigres",
      description: "Resultado final del partido.",
      source: "Liga MX / marcador oficial",
      close_at: "2026-03-28T23:00",
      status: "abierto",
      liquidity: 230000,
      participants: 33,
      confidence: 52,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-16",
      category: "Basket",
      league: "EuroLeague",
      title: "Real Madrid vs Fenerbahce",
      description: "Resultado final EuroLeague.",
      source: "EuroLeague / marcador oficial",
      close_at: "2026-03-29T20:45",
      status: "abierto",
      liquidity: 210000,
      participants: 29,
      confidence: 55,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-17",
      category: "Esports",
      league: "LoL",
      title: "T1 vs Gen.G",
      description: "Serie al mejor de 3.",
      source: "Riot / marcador oficial",
      close_at: "2026-03-29T12:00",
      status: "abierto",
      liquidity: 160000,
      participants: 22,
      confidence: 51,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-18",
      category: "F1",
      league: "Formula 1",
      title: "Verstappen vs Hamilton",
      description: "Duelo directo en clasificación.",
      source: "FIA / timing oficial",
      close_at: "2026-03-30T09:00",
      status: "abierto",
      liquidity: 360000,
      participants: 60,
      confidence: 58,
      icon: "/demo/assets/icons/bolt.svg",
      homeLogo: "/demo/assets/logos/team-verstappen.svg",
      awayLogo: "/demo/assets/logos/team-hamilton.svg",
    },
    {
      id: "mkt-19",
      category: "Rugby",
      league: "Six Nations",
      title: "Irlanda vs Francia",
      description: "Resultado final del test match.",
      source: "Six Nations / marcador oficial",
      close_at: "2026-03-30T16:00",
      status: "abierto",
      liquidity: 140000,
      participants: 19,
      confidence: 49,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-20",
      category: "Tenis",
      league: "WTA",
      title: "Swiatek vs Gauff",
      description: "Resultado final del partido.",
      source: "WTA / marcador oficial",
      close_at: "2026-03-31T13:00",
      status: "abierto",
      liquidity: 180000,
      participants: 26,
      confidence: 54,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-21",
      category: "Basket",
      league: "NBA",
      title: "Celtics vs Warriors",
      description: "Resultado final NBA.",
      source: "NBA / marcador oficial",
      close_at: "2026-03-31T22:30",
      status: "abierto",
      liquidity: 320000,
      participants: 45,
      confidence: 56,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-22",
      category: "Hockey",
      league: "NHL",
      title: "Rangers vs Bruins",
      description: "Resultado final NHL.",
      source: "NHL / marcador oficial",
      close_at: "2026-04-01T21:00",
      status: "abierto",
      liquidity: 210000,
      participants: 28,
      confidence: 53,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-23",
      category: "Vóleibol",
      league: "VNL",
      title: "Brasil vs Italia",
      description: "Resultado final del partido.",
      source: "VNL / marcador oficial",
      close_at: "2026-04-02T18:00",
      status: "abierto",
      liquidity: 170000,
      participants: 21,
      confidence: 51,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-24",
      category: "Handball",
      league: "EHF Champions",
      title: "Kiel vs Barcelona",
      description: "Resultado final del partido.",
      source: "EHF / marcador oficial",
      close_at: "2026-04-03T20:15",
      status: "abierto",
      liquidity: 140000,
      participants: 18,
      confidence: 49,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-25",
      category: "Boxeo",
      league: "Boxing",
      title: "Canelo vs Benavidez",
      description: "Ganador de la pelea.",
      source: "Comisión atlética / marcador oficial",
      close_at: "2026-04-04T23:30",
      status: "abierto",
      liquidity: 260000,
      participants: 36,
      confidence: 55,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-26",
      category: "Dardos",
      league: "PDC Darts",
      title: "Van Gerwen vs Price",
      description: "Ganador del match.",
      source: "PDC / marcador oficial",
      close_at: "2026-04-05T19:30",
      status: "abierto",
      liquidity: 90000,
      participants: 12,
      confidence: 47,
      icon: "/demo/assets/icons/coin.svg",
    },
    {
      id: "mkt-27",
      category: "MotoGP",
      league: "MotoGP",
      title: "Ganador GP de Qatar",
      description: "Piloto ganador de la carrera.",
      source: "MotoGP / timing oficial",
      close_at: "2026-04-06T14:00",
      status: "abierto",
      liquidity: 240000,
      participants: 31,
      confidence: 52,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-28",
      category: "Política",
      league: "Chile",
      title: "Reforma tributaria se aprueba en el Senado",
      description: "Resultado oficial de la votación.",
      source: "Senado de Chile",
      close_at: "2026-04-01T20:00",
      status: "abierto",
      liquidity: 210000,
      participants: 26,
      confidence: 53,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-29",
      category: "Economía",
      league: "LatAm",
      title: "Inflación Chile supera 4% en abril",
      description: "Publicación oficial del IPC.",
      source: "INE",
      close_at: "2026-04-10T12:00",
      status: "abierto",
      liquidity: 180000,
      participants: 22,
      confidence: 49,
      icon: "/demo/assets/icons/coin.svg",
    },
    {
      id: "mkt-30",
      category: "Cripto",
      league: "Global",
      title: "BTC supera los 100k",
      description: "Precio spot en exchanges principales.",
      source: "Indice agregado",
      close_at: "2026-04-08T23:00",
      status: "abierto",
      liquidity: 360000,
      participants: 54,
      confidence: 57,
      icon: "/demo/assets/icons/coin.svg",
    },
    {
      id: "mkt-31",
      category: "Ciencia",
      league: "Global",
      title: "Misión lunar logra aterrizaje exitoso",
      description: "Comunicado oficial de la agencia.",
      source: "Agencia espacial",
      close_at: "2026-04-15T08:00",
      status: "abierto",
      liquidity: 140000,
      participants: 18,
      confidence: 45,
      icon: "/demo/assets/icons/chip.svg",
    },
    {
      id: "mkt-32",
      category: "Clima",
      league: "Chile",
      title: "Temperatura supera 30°C en Santiago",
      description: "Registro oficial del día.",
      source: "Direccion Meteorologica de Chile",
      close_at: "2026-03-26T18:00",
      status: "abierto",
      liquidity: 150000,
      participants: 20,
      confidence: 49,
      icon: "/demo/assets/icons/cloud.svg",
    },
    {
      id: "mkt-33",
      category: "Tecnología",
      league: "Global",
      title: "Empresa X anuncia nueva IA generativa",
      description: "Comunicado oficial.",
      source: "Sala de prensa oficial",
      close_at: "2026-04-08T23:00",
      status: "abierto",
      liquidity: 300000,
      participants: 50,
      confidence: 67,
      icon: "/demo/assets/icons/chip.svg",
    },
    {
      id: "mkt-34",
      category: "Cultura",
      league: "Chile",
      title: "Película chilena gana premio regional",
      description: "Resultado oficial del festival.",
      source: "Comunicado del festival",
      close_at: "2026-04-05T22:00",
      status: "abierto",
      liquidity: 90000,
      participants: 12,
      confidence: 40,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-35",
      category: "Entretenimiento",
      league: "Global",
      title: "Serie X lidera ranking de streaming",
      description: "Top semanal de plataformas.",
      source: "Reporte oficial",
      close_at: "2026-04-12T21:00",
      status: "abierto",
      liquidity: 130000,
      participants: 19,
      confidence: 46,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-42",
      category: "Elecciones",
      league: "Chile",
      title: "Primaria presidencial: gana candidata A",
      description: "Resultado oficial del SERVEL.",
      source: "SERVEL",
      close_at: "2026-05-15T20:00",
      status: "abierto",
      liquidity: 260000,
      participants: 40,
      confidence: 52,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-36",
      category: "Salud",
      league: "Global",
      title: "Se aprueba nueva vacuna estacional",
      description: "Comunicado oficial de organismo regulador.",
      source: "Organismo sanitario",
      close_at: "2026-04-18T10:00",
      status: "abierto",
      liquidity: 170000,
      participants: 23,
      confidence: 48,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-37",
      category: "Geopolítica",
      league: "Global",
      title: "Se firma acuerdo comercial regional",
      description: "Anuncio oficial entre países.",
      source: "Comunicado conjunto",
      close_at: "2026-04-20T18:00",
      status: "abierto",
      liquidity: 190000,
      participants: 28,
      confidence: 50,
      icon: "/demo/assets/icons/bolt.svg",
    },
    {
      id: "mkt-38",
      category: "Empresas",
      league: "Global",
      title: "Empresa X anuncia recompra de acciones",
      description: "Reporte financiero oficial.",
      source: "Hecho esencial",
      close_at: "2026-04-22T22:00",
      status: "abierto",
      liquidity: 210000,
      participants: 31,
      confidence: 52,
      icon: "/demo/assets/icons/coin.svg",
    },
    {
      id: "mkt-39",
      category: "Energía",
      league: "Global",
      title: "Precio del Brent supera USD 100",
      description: "Cierre oficial del mercado.",
      source: "Indice energetico",
      close_at: "2026-04-25T23:00",
      status: "abierto",
      liquidity: 260000,
      participants: 35,
      confidence: 54,
      icon: "/demo/assets/icons/cloud.svg",
    },
    {
      id: "mkt-40",
      category: "Justicia",
      league: "Chile",
      title: "Se aprueba nueva ley de datos",
      description: "Votacion final en la Camara.",
      source: "Camara de Diputados",
      close_at: "2026-04-28T19:00",
      status: "abierto",
      liquidity: 150000,
      participants: 20,
      confidence: 47,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-41",
      category: "Medioambiente",
      league: "Chile",
      title: "Se declara nuevo parque nacional",
      description: "Decreto oficial publicado.",
      source: "Ministerio del Medio Ambiente",
      close_at: "2026-05-02T17:00",
      status: "abierto",
      liquidity: 120000,
      participants: 16,
      confidence: 44,
      icon: "/demo/assets/icons/cloud.svg",
    },
    {
      id: "mkt-28",
      category: "Golf",
      league: "PGA Tour",
      title: "Ganador del Masters de Augusta",
      description: "Campeón del torneo.",
      source: "PGA / marcador oficial",
      close_at: "2026-04-07T22:00",
      status: "abierto",
      liquidity: 180000,
      participants: 24,
      confidence: 50,
      icon: "/demo/assets/icons/trophy.svg",
    },
    {
      id: "mkt-29",
      category: "Cricket",
      league: "IPL",
      title: "Mumbai vs Chennai",
      description: "Resultado final del partido.",
      source: "IPL / marcador oficial",
      close_at: "2026-04-08T15:30",
      status: "abierto",
      liquidity: 200000,
      participants: 27,
      confidence: 52,
      icon: "/demo/assets/icons/ball.svg",
    },
    {
      id: "mkt-30",
      category: "Ciclismo",
      league: "UCI World Tour",
      title: "Ganador etapa 1",
      description: "Ciclista ganador de etapa.",
      source: "UCI / timing oficial",
      close_at: "2026-04-09T14:30",
      status: "abierto",
      liquidity: 140000,
      participants: 18,
      confidence: 47,
      icon: "/demo/assets/icons/bolt.svg",
    },
  ],
  live: [
    {
      id: "live-1",
      matchId: "fx-1",
      title: "Colo-Colo vs Universidad de Chile",
      category: "Deportes",
      minute: 67,
      score: "1-0",
      yesOdd: 1.72,
      noOdd: 2.25,
      homeLogo: "/demo/assets/logos/team-colo-colo.svg",
      awayLogo: "/demo/assets/logos/team-la-u.svg",
    },
    {
      id: "live-2",
      matchId: "fx-3",
      title: "Lakers vs Heat",
      category: "NBA",
      minute: 33,
      score: "54-48",
      yesOdd: 1.58,
      noOdd: 2.45,
      homeLogo: "/demo/assets/logos/team-lakers.svg",
      awayLogo: "/demo/assets/logos/team-heat.svg",
    },
    {
      id: "live-3",
      matchId: "fx-13",
      title: "Huachipato vs Cobresal",
      category: "Primera División",
      minute: 52,
      score: "0-0",
      yesOdd: 1.95,
      noOdd: 2.05,
      homeLogo: "/demo/assets/logos/team-huachipato.svg",
      awayLogo: "/demo/assets/logos/team-cobresal.svg",
    },
    {
      id: "live-4",
      matchId: "fx-20",
      title: "Inter Miami vs LAFC",
      category: "MLS",
      minute: 41,
      score: "2-1",
      yesOdd: 1.62,
      noOdd: 2.35,
      homeLogo: "/demo/assets/logos/team-mia.svg",
      awayLogo: "/demo/assets/logos/team-lafc.svg",
    },
  ],
  fixtures: [
    {
      id: "fx-1",
      league: "Primera División",
      home: "Colo-Colo",
      away: "Universidad de Chile",
      time: "18:30",
      odds: "1.85",
      day: "Hoy",
      homeLogo: "/demo/assets/logos/team-colo-colo.svg",
      awayLogo: "/demo/assets/logos/team-la-u.svg",
    },
    {
      id: "fx-2",
      league: "Champions League",
      home: "PSG",
      away: "Milan",
      time: "20:00",
      odds: "2.05",
      day: "Hoy",
      homeLogo: "/demo/assets/logos/team-psg.svg",
      awayLogo: "/demo/assets/logos/team-milan.svg",
    },
    {
      id: "fx-3",
      league: "NBA",
      home: "Lakers",
      away: "Heat",
      time: "22:15",
      odds: "1.72",
      day: "Mañana",
      homeLogo: "/demo/assets/logos/team-lakers.svg",
      awayLogo: "/demo/assets/logos/team-heat.svg",
    },
    {
      id: "fx-4",
      league: "ATP Tour",
      home: "Alcaraz",
      away: "Medvedev",
      time: "15:40",
      odds: "1.64",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-alcaraz.svg",
      awayLogo: "/demo/assets/logos/team-medvedev.svg",
    },
    {
      id: "fx-5",
      league: "Primera División",
      home: "Universidad Católica",
      away: "Palestino",
      time: "20:30",
      odds: "1.95",
      day: "Mañana",
      homeLogo: "/demo/assets/logos/team-uc.svg",
      awayLogo: "/demo/assets/logos/team-palestino.svg",
    },
    {
      id: "fx-6",
      league: "Premier League",
      home: "Arsenal",
      away: "Chelsea",
      time: "17:00",
      odds: "1.88",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-ars.svg",
      awayLogo: "/demo/assets/logos/team-che.svg",
    },
    {
      id: "fx-7",
      league: "LaLiga",
      home: "Real Madrid",
      away: "Barcelona",
      time: "21:00",
      odds: "2.10",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-rma.svg",
      awayLogo: "/demo/assets/logos/team-bar.svg",
    },
    {
      id: "fx-8",
      league: "Serie A",
      home: "Juventus",
      away: "Inter",
      time: "20:45",
      odds: "2.05",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-juv.svg",
      awayLogo: "/demo/assets/logos/team-int.svg",
    },
    {
      id: "fx-9",
      league: "Bundesliga",
      home: "Bayern",
      away: "Dortmund",
      time: "19:30",
      odds: "1.90",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-bay.svg",
      awayLogo: "/demo/assets/logos/team-bvb.svg",
    },
    {
      id: "fx-10",
      league: "Ligue 1",
      home: "PSG",
      away: "Lyon",
      time: "20:30",
      odds: "1.70",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-psg.svg",
      awayLogo: "/demo/assets/logos/team-lyo.svg",
    },
    {
      id: "fx-11",
      league: "NFL",
      home: "Chiefs",
      away: "49ers",
      time: "23:00",
      odds: "1.80",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-kc.svg",
      awayLogo: "/demo/assets/logos/team-sf.svg",
    },
    {
      id: "fx-12",
      league: "MLB",
      home: "Yankees",
      away: "Dodgers",
      time: "21:15",
      odds: "1.92",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-nyy.svg",
      awayLogo: "/demo/assets/logos/team-lad.svg",
    },
    {
      id: "fx-13",
      league: "Primera División",
      home: "Huachipato",
      away: "Cobresal",
      time: "19:00",
      odds: "1.96",
      day: "Hoy",
      homeLogo: "/demo/assets/logos/team-huachipato.svg",
      awayLogo: "/demo/assets/logos/team-cobresal.svg",
    },
    {
      id: "fx-14",
      league: "Primera División",
      home: "Everton",
      away: "Unión Española",
      time: "20:30",
      odds: "2.02",
      day: "Mañana",
      homeLogo: "/demo/assets/logos/team-everton.svg",
      awayLogo: "/demo/assets/logos/team-union.svg",
    },
    {
      id: "fx-15",
      league: "Primera División",
      home: "Audax Italiano",
      away: "O'Higgins",
      time: "21:00",
      odds: "1.88",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-audax.svg",
      awayLogo: "/demo/assets/logos/team-ohiggins.svg",
    },
    {
      id: "fx-16",
      league: "Primera B",
      home: "Wanderers",
      away: "Temuco",
      time: "16:00",
      odds: "1.84",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-wanderers.svg",
      awayLogo: "/demo/assets/logos/team-temuco.svg",
    },
    {
      id: "fx-17",
      league: "Primera B",
      home: "Cobreloa",
      away: "Rangers",
      time: "18:00",
      odds: "1.92",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-cobreloa.svg",
      awayLogo: "/demo/assets/logos/team-rangers.svg",
    },
    {
      id: "fx-18",
      league: "Copa Chile",
      home: "Colo-Colo",
      away: "Universidad Católica",
      time: "19:30",
      odds: "1.90",
      day: "Mañana",
      homeLogo: "/demo/assets/logos/team-colo-colo.svg",
      awayLogo: "/demo/assets/logos/team-uc.svg",
    },
    {
      id: "fx-19",
      league: "Copa Chile",
      home: "Universidad de Chile",
      away: "Palestino",
      time: "20:00",
      odds: "1.96",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/team-la-u.svg",
      awayLogo: "/demo/assets/logos/team-palestino.svg",
    },
    {
      id: "fx-20",
      league: "MLS",
      home: "Inter Miami",
      away: "LAFC",
      time: "22:00",
      odds: "2.12",
      day: "Semana",
      homeLogo: "/demo/assets/logos/team-mia.svg",
      awayLogo: "/demo/assets/logos/team-lafc.svg",
    },
    {
      id: "fx-21",
      league: "Copa Libertadores",
      home: "Flamengo",
      away: "River Plate",
      time: "21:30",
      odds: "2.05",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-libertadores.svg",
      awayLogo: "/demo/assets/logos/liga-libertadores.svg",
    },
    {
      id: "fx-22",
      league: "Copa Sudamericana",
      home: "São Paulo",
      away: "LDU Quito",
      time: "21:30",
      odds: "1.98",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-sudamericana.svg",
      awayLogo: "/demo/assets/logos/liga-sudamericana.svg",
    },
    {
      id: "fx-23",
      league: "Liga MX",
      home: "Club América",
      away: "Tigres",
      time: "23:00",
      odds: "1.94",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-ligamx.svg",
      awayLogo: "/demo/assets/logos/liga-ligamx.svg",
    },
    {
      id: "fx-24",
      league: "EuroLeague",
      home: "Real Madrid",
      away: "Fenerbahce",
      time: "20:45",
      odds: "1.76",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/liga-euroleague.svg",
      awayLogo: "/demo/assets/logos/liga-euroleague.svg",
    },
    {
      id: "fx-25",
      league: "WTA",
      home: "Swiatek",
      away: "Gauff",
      time: "13:00",
      odds: "1.62",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-wta.svg",
      awayLogo: "/demo/assets/logos/liga-wta.svg",
    },
    {
      id: "fx-26",
      league: "LoL",
      home: "T1",
      away: "Gen.G",
      time: "12:00",
      odds: "1.78",
      day: "Hoy",
      homeLogo: "/demo/assets/logos/liga-lol.svg",
      awayLogo: "/demo/assets/logos/liga-lol.svg",
    },
    {
      id: "fx-27",
      league: "Formula 1",
      home: "Verstappen",
      away: "Hamilton",
      time: "09:00",
      odds: "1.85",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/liga-f1.svg",
      awayLogo: "/demo/assets/logos/liga-f1.svg",
    },
    {
      id: "fx-28",
      league: "Six Nations",
      home: "Irlanda",
      away: "Francia",
      time: "16:00",
      odds: "1.88",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/liga-sixnations.svg",
      awayLogo: "/demo/assets/logos/liga-sixnations.svg",
    },
    {
      id: "fx-29",
      league: "NHL",
      home: "Rangers",
      away: "Bruins",
      time: "21:00",
      odds: "1.90",
      day: "Hoy",
      homeLogo: "/demo/assets/logos/liga-nhl.svg",
      awayLogo: "/demo/assets/logos/liga-nhl.svg",
    },
    {
      id: "fx-30",
      league: "VNL",
      home: "Brasil",
      away: "Italia",
      time: "18:00",
      odds: "1.78",
      day: "Mañana",
      homeLogo: "/demo/assets/logos/liga-vnl.svg",
      awayLogo: "/demo/assets/logos/liga-vnl.svg",
    },
    {
      id: "fx-31",
      league: "EHF Champions",
      home: "Kiel",
      away: "Barcelona",
      time: "20:15",
      odds: "1.86",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-ehf.svg",
      awayLogo: "/demo/assets/logos/liga-ehf.svg",
    },
    {
      id: "fx-32",
      league: "Boxing",
      home: "Canelo",
      away: "Benavidez",
      time: "23:30",
      odds: "1.74",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/liga-boxing.svg",
      awayLogo: "/demo/assets/logos/liga-boxing.svg",
    },
    {
      id: "fx-33",
      league: "PDC Darts",
      home: "Van Gerwen",
      away: "Price",
      time: "19:30",
      odds: "1.82",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-darts.svg",
      awayLogo: "/demo/assets/logos/liga-darts.svg",
    },
    {
      id: "fx-34",
      league: "MotoGP",
      home: "Bagnaia",
      away: "Marquez",
      time: "14:00",
      odds: "1.88",
      day: "Fin de semana",
      homeLogo: "/demo/assets/logos/liga-motogp.svg",
      awayLogo: "/demo/assets/logos/liga-motogp.svg",
    },
    {
      id: "fx-35",
      league: "PGA Tour",
      home: "Scheffler",
      away: "McIlroy",
      time: "22:00",
      odds: "1.92",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-pga.svg",
      awayLogo: "/demo/assets/logos/liga-pga.svg",
    },
    {
      id: "fx-36",
      league: "IPL",
      home: "Mumbai",
      away: "Chennai",
      time: "15:30",
      odds: "1.84",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-ipl.svg",
      awayLogo: "/demo/assets/logos/liga-ipl.svg",
    },
    {
      id: "fx-37",
      league: "UCI World Tour",
      home: "Etapa 1",
      away: "Etapa 2",
      time: "14:30",
      odds: "1.90",
      day: "Semana",
      homeLogo: "/demo/assets/logos/liga-uci.svg",
      awayLogo: "/demo/assets/logos/liga-uci.svg",
    },
  ],
  matches: [
    {
      id: "fx-1",
      possession: [52, 48],
      shots: [11, 7],
      corners: [6, 4],
      fouls: [13, 10],
      odds: { home: 1.85, draw: 3.1, away: 2.2 },
    },
    {
      id: "fx-2",
      possession: [49, 51],
      shots: [9, 8],
      corners: [5, 6],
      fouls: [12, 9],
      odds: { home: 2.05, draw: 3.3, away: 2.0 },
    },
    {
      id: "fx-3",
      possession: [55, 45],
      shots: [18, 14],
      corners: [7, 5],
      fouls: [15, 12],
      odds: { home: 1.72, draw: 3.4, away: 2.4 },
    },
    {
      id: "fx-4",
      possession: [50, 50],
      shots: [12, 11],
      corners: [4, 4],
      fouls: [9, 8],
      odds: { home: 1.64, draw: 2.9, away: 2.5 },
    },
    {
      id: "fx-13",
      possession: [54, 46],
      shots: [10, 8],
      corners: [5, 3],
      fouls: [12, 14],
      odds: { home: 1.96, draw: 3.2, away: 2.6 },
    },
    {
      id: "fx-14",
      possession: [48, 52],
      shots: [9, 11],
      corners: [4, 6],
      fouls: [15, 11],
      odds: { home: 2.02, draw: 3.1, away: 2.4 },
    },
    {
      id: "fx-15",
      possession: [51, 49],
      shots: [12, 9],
      corners: [6, 4],
      fouls: [10, 13],
      odds: { home: 1.88, draw: 3.0, away: 2.5 },
    },
    {
      id: "fx-16",
      possession: [53, 47],
      shots: [11, 7],
      corners: [5, 2],
      fouls: [14, 16],
      odds: { home: 1.84, draw: 3.2, away: 2.7 },
    },
    {
      id: "fx-17",
      possession: [50, 50],
      shots: [8, 8],
      corners: [3, 3],
      fouls: [12, 12],
      odds: { home: 1.92, draw: 3.1, away: 2.6 },
    },
    {
      id: "fx-18",
      possession: [55, 45],
      shots: [14, 9],
      corners: [7, 4],
      fouls: [11, 10],
      odds: { home: 1.9, draw: 3.2, away: 2.3 },
    },
    {
      id: "fx-19",
      possession: [49, 51],
      shots: [10, 10],
      corners: [4, 5],
      fouls: [13, 12],
      odds: { home: 1.96, draw: 3.0, away: 2.4 },
    },
    {
      id: "fx-20",
      possession: [47, 53],
      shots: [9, 12],
      corners: [3, 6],
      fouls: [16, 11],
      odds: { home: 2.12, draw: 3.3, away: 2.1 },
    },
    {
      id: "fx-21",
      possession: [52, 48],
      shots: [13, 10],
      corners: [5, 4],
      fouls: [14, 13],
      odds: { home: 2.05, draw: 3.2, away: 2.4 },
    },
    {
      id: "fx-22",
      possession: [50, 50],
      shots: [11, 11],
      corners: [5, 5],
      fouls: [12, 12],
      odds: { home: 1.98, draw: 3.1, away: 2.5 },
    },
    {
      id: "fx-23",
      possession: [51, 49],
      shots: [12, 9],
      corners: [6, 4],
      fouls: [13, 14],
      odds: { home: 1.94, draw: 3.1, away: 2.6 },
    },
    {
      id: "fx-24",
      possession: [54, 46],
      shots: [17, 14],
      corners: [8, 6],
      fouls: [15, 12],
      odds: { home: 1.76, draw: 3.0, away: 2.2 },
    },
    {
      id: "fx-25",
      possession: [50, 50],
      shots: [10, 10],
      corners: [3, 3],
      fouls: [8, 8],
      odds: { home: 1.62, draw: 2.9, away: 2.4 },
    },
    {
      id: "fx-26",
      possession: [49, 51],
      shots: [12, 13],
      corners: [4, 4],
      fouls: [10, 10],
      odds: { home: 1.78, draw: 3.0, away: 2.2 },
    },
    {
      id: "fx-27",
      possession: [52, 48],
      shots: [9, 8],
      corners: [2, 2],
      fouls: [6, 6],
      odds: { home: 1.85, draw: 2.8, away: 2.2 },
    },
    {
      id: "fx-28",
      possession: [53, 47],
      shots: [11, 9],
      corners: [3, 3],
      fouls: [14, 15],
      odds: { home: 1.88, draw: 2.9, away: 2.3 },
    },
    {
      id: "fx-29",
      possession: [52, 48],
      shots: [28, 24],
      corners: [0, 0],
      fouls: [6, 7],
      odds: { home: 1.9, draw: 3.1, away: 2.1 },
    },
    {
      id: "fx-30",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.78, draw: 0, away: 2.2 },
    },
    {
      id: "fx-31",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.86, draw: 0, away: 2.3 },
    },
    {
      id: "fx-32",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.74, draw: 0, away: 2.2 },
    },
    {
      id: "fx-33",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.82, draw: 0, away: 2.1 },
    },
    {
      id: "fx-34",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.88, draw: 0, away: 2.2 },
    },
    {
      id: "fx-35",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.92, draw: 0, away: 2.1 },
    },
    {
      id: "fx-36",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.84, draw: 0, away: 2.2 },
    },
    {
      id: "fx-37",
      possession: [0, 0],
      shots: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      odds: { home: 1.9, draw: 0, away: 2.1 },
    },
  ],
  standings: [
    {
      league: "Primera División",
      updated: "2026-03-20",
      rows: [
        { team: "Colo-Colo", played: 8, w: 5, d: 2, l: 1, gf: 14, pts: 17, logo: "/demo/assets/logos/team-colo-colo.svg" },
        { team: "Universidad de Chile", played: 8, w: 5, d: 1, l: 2, gf: 13, pts: 16, logo: "/demo/assets/logos/team-la-u.svg" },
        { team: "Universidad Católica", played: 8, w: 4, d: 2, l: 2, gf: 12, pts: 14, logo: "/demo/assets/logos/team-uc.svg" },
        { team: "Palestino", played: 8, w: 3, d: 3, l: 2, gf: 10, pts: 12, logo: "/demo/assets/logos/team-palestino.svg" }
      ],
    },
    {
      league: "Premier League",
      updated: "2026-03-20",
      rows: [
        { team: "Arsenal", played: 27, w: 18, d: 5, l: 4, gf: 55, pts: 59, logo: "/demo/assets/logos/team-ars.svg" },
        { team: "Chelsea", played: 27, w: 16, d: 6, l: 5, gf: 48, pts: 54, logo: "/demo/assets/logos/team-che.svg" }
      ],
    }
  ],
  news: [
    {
      id: "nw-1",
      title: "Se actualizan cuotas para el clásico",
      time: "Hace 5 min",
    },
    {
      id: "nw-2",
      title: "Mercados de clima con alta participación",
      time: "Hace 22 min",
    },
    {
      id: "nw-3",
      title: "Nuevos eventos de tecnología disponibles",
      time: "Hace 1 h",
    },
    {
      id: "nw-4",
      title: "Primera B suma nuevos duelos para el fin de semana",
      time: "Hace 2 h",
    },
    {
      id: "nw-5",
      title: "Libertadores y Sudamericana abren fase de grupos",
      time: "Hace 3 h",
    },
    {
      id: "nw-6",
      title: "NBA: Celtics vs Warriors con cuotas actualizadas",
      time: "Hace 4 h",
    },
  ],
};

const logoCache = new Map();
const logoCacheTtlMs = 1000 * 60 * 60 * 24 * 14;

const getCachedLogo = (key) => {
  const entry = logoCache.get(key);
  if (!entry) return "";
  if (Date.now() - entry.at > logoCacheTtlMs) {
    logoCache.delete(key);
    return "";
  }
  return entry.url || "";
};

const setCachedLogo = (key, url) => {
  if (!url) return;
  logoCache.set(key, { url, at: Date.now() });
};

const fetchJson = (url) =>
  new Promise((resolve) => {
    https
      .get(url, (resp) => {
        let data = "";
        resp.on("data", (chunk) => {
          data += chunk;
        });
        resp.on("end", () => {
          try {
            resolve(JSON.parse(data));
          } catch {
            resolve(null);
          }
        });
      })
      .on("error", () => resolve(null));
  });

const resolveTeamLogo = async (teamName) => {
  if (!teamName) return "";
  const cacheKey = `team:${teamName}`;
  const cached = getCachedLogo(cacheKey);
  if (cached) return cached;
  const url = `https://www.thesportsdb.com/api/v1/json/3/searchteams.php?t=${encodeURIComponent(teamName)}`;
  const data = await fetchJson(url);
  const logo =
    data?.teams?.[0]?.strTeamBadge ||
    data?.teams?.[0]?.strTeamLogo ||
    data?.teams?.[0]?.strTeamFanart1 ||
    "";
  if (logo) setCachedLogo(cacheKey, logo);
  return logo || "";
};

const resolveLeagueLogo = async (leagueName) => {
  if (!leagueName) return "";
  const cacheKey = `league:${leagueName}`;
  const cached = getCachedLogo(cacheKey);
  if (cached) return cached;
  const url = `https://www.thesportsdb.com/api/v1/json/3/search_all_leagues.php?l=${encodeURIComponent(leagueName)}`;
  const data = await fetchJson(url);
  const logo = data?.countries?.[0]?.strBadge || data?.countries?.[0]?.strLogo || "";
  if (logo) setCachedLogo(cacheKey, logo);
  return logo || "";
};

const resolveSportIcon = async (sportName) => {
  if (!sportName) return "";
  const cacheKey = `sport:${sportName}`;
  const cached = getCachedLogo(cacheKey);
  if (cached) return cached;
  const data = await fetchJson("https://www.thesportsdb.com/api/v1/json/3/all_sports.php");
  const match = (data?.sports || []).find((item) => item.strSport === sportName);
  const icon = match?.strSportThumb || match?.strSportIconGreen || "";
  if (icon) setCachedLogo(cacheKey, icon);
  return icon || "";
};

const sendJson = (res, payload) => {
  res.writeHead(200, {
    "Content-Type": "application/json; charset=utf-8",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
  });
  res.end(JSON.stringify(payload));
};

const safePath = (urlPath) => {
  const cleaned = decodeURIComponent(urlPath.split("?")[0]);
  if (cleaned === "/favicon.ico") {
    return path.join(rootDir, "demo", "assets", "icon-192.svg");
  }
  if (cleaned === "/") return path.join(rootDir, "index.html");
  if (cleaned === "/demo") return path.join(rootDir, "demo", "index.html");
  if (cleaned === "/demo/") return path.join(rootDir, "demo", "index.html");
  const resolved = path.normalize(path.join(rootDir, cleaned));
  if (!resolved.startsWith(rootDir)) {
    return path.join(rootDir, "index.html");
  }
  return resolved;
};

const serveFile = (filePath, res) => {
  fs.stat(filePath, (err, stat) => {
    if (err || !stat.isFile()) {
      res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("404 - Archivo no encontrado");
      return;
    }
    const ext = path.extname(filePath).toLowerCase();
    const contentType = mimeTypes[ext] || "application/octet-stream";
    res.writeHead(200, { "Content-Type": contentType });
    fs.createReadStream(filePath).pipe(res);
  });
};

const server = http.createServer((req, res) => {
  if (req.method !== "GET") {
    res.writeHead(405, { "Content-Type": "text/plain; charset=utf-8" });
    res.end("Metodo no permitido");
    return;
  }
  if ((req.url || "").startsWith("/api/")) {
    const endpoint = (req.url || "").split("?")[0];
    if (endpoint === "/api/logos/team") {
      const name = new URL(req.url, "http://localhost").searchParams.get("name") || "";
      resolveTeamLogo(name).then((logo) => sendJson(res, { logo }));
      return;
    }
    if (endpoint === "/api/logos/league") {
      const name = new URL(req.url, "http://localhost").searchParams.get("name") || "";
      resolveLeagueLogo(name).then((logo) => sendJson(res, { logo }));
      return;
    }
    if (endpoint === "/api/logos/sport") {
      const name = new URL(req.url, "http://localhost").searchParams.get("name") || "";
      resolveSportIcon(name).then((logo) => sendJson(res, { logo }));
      return;
    }
    if (endpoint === "/api/markets") return sendJson(res, apiData.markets);
    if (endpoint === "/api/live") return sendJson(res, apiData.live);
    if (endpoint === "/api/fixtures") return sendJson(res, apiData.fixtures);
    if (endpoint === "/api/banners") return sendJson(res, apiData.banners);
    if (endpoint === "/api/leagues") return sendJson(res, apiData.leagues);
    if (endpoint === "/api/news") return sendJson(res, apiData.news);
    if (endpoint === "/api/matches") return sendJson(res, apiData.matches);
    if (endpoint === "/api/standings") return sendJson(res, apiData.standings || []);
    return sendJson(res, { error: "Not found" });
  }
  const filePath = safePath(req.url || "/");
  serveFile(filePath, res);
});

let activePort = port;

const startServer = (nextPort) => {
  activePort = nextPort;
  server.listen(activePort, () => {
    console.log(`Servidor local activo en http://localhost:${activePort}`);
  });
};

server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    const fallbackPort = activePort + 1;
    console.warn(`Puerto ${activePort} en uso. Probando ${fallbackPort}...`);
    setTimeout(() => startServer(fallbackPort), 300);
    return;
  }
  throw err;
});

startServer(port);
